name: 'motion_champion'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  netease:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install requests'
      run: python -m pip install --upgrade requests
    - name: 'Install hashlib'
      run: python -m pip install --upgrade hashlib
    - name: 'Install json'
      run: python -m pip install --upgrade json
    - name: 'Install datetime'
      run: python -m pip install --upgrade datetime
    - name: 'Install time'
      run: python -m pip install --upgrade time
    - name: 'motion_champion'
      run: python signin.py
